### ISSUE TITLE
Note cut doesn't work on channel 3

### ISSUE THREAD

**Issue by SuperDisk** [ISSOtm/fortISSimO#10]
Effect `Exx` Note Cut does not seem to work on the wave channel.

**Comment by ISSOtm** [comment]
I believe it works fine (turns CH3 off and on again), but relies on behaviour not emulated by hUGETracker. I couldn't figure out how to patch hT accordingly for testing, so have you been able to reproduce the issue on SameBoy and/or hardware? (I'm more confident with SameBoy's APU emulation, specifically.)

**Comment by ISSOtm** [comment]
This does appear to be a hUGETracker problem; a single `E01` cuts in a generated ROM, but not in hT. What should we do? I'd rather not switch to another, less compat/efficient solution (since it works on hardware), but I haven't figured out how to implement this into hT :S

**Comment by ISSOtm** [comment]
(Closing as it's not a fO issue, but tell me if you want me to open an issue on hT's tracker; depending on what's decided about the above.)
