### ISSUE TITLE
Wave channel isn't cut when starting a new song.

### ISSUE THREAD

**Issue by eievui5** [ISSOtm/fortISSimO#12]
I'm guessing this was missed when testing because only one song is played at a time, but when the song changes the wave channel will linger for a bit until the new song uses it.

**Comment by eievui5** [comment]
This might actually apply to *all* channels, I'm just only noticing it on wave.

**Comment by ISSOtm** [comment]
It does indeed apply to all channels.

I think this is, however, intended behaviour?
For one thing, hUGEDriver (seems to) do the same.
This is also problematic when combined with SFX: which channels should be cleared? Relying on `hUGE_MutedChannels` is possible, but I don't know if it's desirable.

**Comment by eievui5** [comment]
Here's a potential fix if you decide this isn't intended.
Putting this at the beginning of `hUGE_StartSong` resets only the channels which hUGE has permission to use:
```
	ldh a, [hUGE_MutedChannels]
	ld b, a
	xor a, a

	rr b
	jr c, :+
	ldh [rNR12], a
:
	rr b
	jr c, :+
	ldh [rNR22], a
:
	rr b
	jr c, :+
	ldh [rNR32], a
:
	rr b
	jr c, :+
	ldh [rNR42], a
:
```

**Comment by ISSOtm** [comment]
I don't think I want to clear all channels in the driver when the init function is called, so that smooth transition between tracks are possible if desired.
I'll keep this open as a reminder to mention it in the manual, unless someone disagrees with the above.

**Comment by ISSOtm** [comment]
Well, I think silencing the channels is a better default than not, so I implemented that in the commit above. @eievui5, please let me know if the issue is correctly fixed?

**Comment by ISSOtm** [comment]
Note that I didn't implement the proposed patch because it turns off the DACs (except for CH3, for which I'm not sure zeroing NR32 is the perfect solution?). Avoiding that should avoid popping when starting a song, I think. Feedback on that would also be appreciated!

**Comment by eievui5** [comment]
Thank you, this works great.
