### ISSUE TITLE
Note Delay seems to be off after number of loops

### ISSUE THREAD

**Issue by sttng** [ISSOtm/fortISSimO#16]
I don't really now how to describe it properly. Just listen to the example for a number of loops (at least 20 or so) and it seems like the beat changes - likely a note is missed or something.

[Bells-Note-Delay.zip](https://github.com/ISSOtm/fortISSimO/files/12447243/Bells-Note-Delay.zip)

**Comment by sttng** [comment]
Couldn't replicate on real hardware

**Comment by ISSOtm** [comment]
Considering the results that were gotten, it seems like it was an auditory illusion, somehow. Go figure, humans are *weird*.
