### ISSUE TITLE
Wrong kind for wave instr #0!

### ISSUE THREAD

**Issue by Beatscribe** [ISSOtm/fortISSimO#30]
When attempting to convert [this song](https://drive.google.com/file/d/17vWTOV3W3QiRNwwsNFBBKTJU2FO5rbH4/view?usp=sharing) to asm with teNOR, I get the following error:

ratt@Jesses-MacBook-Pro fortISSimO % cargo run beatscribe-techno-boat.uge tb.asm
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/teNOR beatscribe-techno-boat.uge tb.asm`
thread 'main' panicked at teNOR/src/uge.rs:133:17:
Wrong kind for wave instr #0! (Square { initial_volume: 11, envelope_dir: Down, envelope_pace: 1, sweep_time: 1, sweep_dir: Down, sweep_shift: 3, duty: Percent50 })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

The song is built in hugetracker 1.11 with f0 loaded into it. It uses sub patterns and most other common commands needed in hUGEDriver songs.

**Comment by ISSOtm** [comment]
Fixed by af12fe8
