### ISSUE TITLE
Arpeggio problem

### ISSUE THREAD

**Issue by SuperDisk** [ISSOtm/fortISSimO#7]
Arpeggios do not seem to work. I've included a sample module, and recordings of each driver.

[arp.zip](https://github.com/ISSOtm/fortISSimO/files/10473667/arp.zip)

**Comment by ISSOtm** [comment]
How is that possible? We dispatch from a global counter!

https://github.com/ISSOtm/fortISSimO/blob/0233a0e5cd5922c3db7fb4880b31371878d83d16/fortISSimO.asm#L1106-L1115

...Oh wait, [`rra` always resets Z](https://rgbds.gbdev.io/docs/v0.6.1/gbz80.7/#RRA).

**Comment by ISSOtm** [comment]
Turns out fO's arps use the offsets in freq space, not note space. Oops.
